export const actionType={
    REQUEST_LOGIN :'REQUEST_LOGIN',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED' ,
    LOGOUT:'LOGOUT',
    REQUEST_SIGNUP :'REQUEST_LOGIN',
    SIGNUP_SUCCESS:'LOGIN_SUCCESS',
    SIGNUP_FAILED:'LOGIN_FAILED' ,

} 