export const actionType = {
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    REQUEST_SIGNUP: 'REQUEST_LOGIN',
    SIGNUP_SUCCESS: 'LOGIN_SUCCESS',
    SIGNUP_FAILED: 'LOGIN_FAILED',

    GET_ALL_DATA: 'GET_ALL_DATA',
    ADD_POST: 'ADD_POST',
    EDIT_POST: 'EDIT_POST',
    DELETE_POST: 'DELETE_POST',
    DELETE_COMMENT: 'DELETE_COMMENT',
    ADD_COMMENT: 'ADD_COMMENT'
} 